// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";

// src/data/mockData.ts
var womenProducts = [
  {
    id: "w1",
    name: "Banarasi Silk Saree",
    slug: "banarasi-silk-saree-red",
    description: "Elegant handwoven Banarasi silk saree with traditional motifs",
    categoryId: "1-1-1",
    categoryName: "Silk Sarees",
    tags: ["silk", "banarasi", "traditional"],
    isActive: true,
    isFeatured: true,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "wv1",
      productId: "w1",
      sku: "BS-RED-001",
      color: "Red",
      colorHex: "#DC143C",
      price: 8999,
      compareAtPrice: 14999,
      costPrice: 6e3,
      stockQuantity: 15,
      isActive: true,
      images: [{
        id: "wi1",
        variantId: "wv1",
        url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800",
        altText: "Red Banarasi Saree",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 8999,
    maxPrice: 8999,
    avgRating: 4.8,
    reviewCount: 156,
    totalStock: 15
  },
  {
    id: "w2",
    name: "Cotton Kurti Set",
    slug: "floral-cotton-kurti",
    description: "Comfortable floral printed cotton kurti perfect for daily wear",
    categoryId: "1-3",
    categoryName: "Kurtis",
    tags: ["cotton", "kurti", "daily wear"],
    isActive: true,
    isFeatured: false,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "wv2",
      productId: "w2",
      sku: "CK-BLU-001",
      color: "Blue",
      colorHex: "#4169E1",
      price: 1299,
      compareAtPrice: 2199,
      costPrice: 800,
      stockQuantity: 45,
      isActive: true,
      images: [{
        id: "wi2",
        variantId: "wv2",
        url: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=800",
        altText: "Floral Kurti",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 1299,
    maxPrice: 1299,
    avgRating: 4.5,
    reviewCount: 89,
    totalStock: 45
  },
  {
    id: "w3",
    name: "Designer Salwar Suit",
    slug: "anarkali-salwar-suit",
    description: "Beautiful Anarkali style salwar suit with embroidery",
    categoryId: "1-2",
    categoryName: "Chudithars & Salwars",
    tags: ["salwar", "anarkali", "party wear"],
    isActive: true,
    isFeatured: true,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "wv3",
      productId: "w3",
      sku: "SS-PNK-001",
      color: "Pink",
      colorHex: "#FF69B4",
      price: 3499,
      compareAtPrice: 5999,
      costPrice: 2200,
      stockQuantity: 28,
      isActive: true,
      images: [{
        id: "wi3",
        variantId: "wv3",
        url: "https://images.unsplash.com/photo-1585646975848-986d86653f84?w=800",
        altText: "Anarkali Suit",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 3499,
    maxPrice: 3499,
    avgRating: 4.7,
    reviewCount: 124,
    totalStock: 28
  }
];
var menProducts = [
  {
    id: "m1",
    name: "Premium Cotton T-Shirt",
    slug: "cotton-round-neck-tshirt",
    description: "Soft premium cotton t-shirt with comfortable fit",
    categoryId: "2-2-2",
    categoryName: "Round Neck T-Shirts",
    tags: ["t-shirt", "cotton", "casual"],
    isActive: true,
    isFeatured: false,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "mv1",
      productId: "m1",
      sku: "TS-BLK-M",
      size: "M",
      color: "Black",
      colorHex: "#000000",
      price: 599,
      compareAtPrice: 999,
      costPrice: 350,
      stockQuantity: 120,
      isActive: true,
      images: [{
        id: "mi1",
        variantId: "mv1",
        url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
        altText: "Black T-Shirt",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 599,
    maxPrice: 599,
    avgRating: 4.6,
    reviewCount: 342,
    totalStock: 120
  },
  {
    id: "m2",
    name: "Branded Polo Shirt",
    slug: "polo-collar-shirt",
    description: "Classic polo shirt with brand logo",
    categoryId: "2-2-1",
    categoryName: "Polo T-Shirts",
    tags: ["polo", "branded", "casual"],
    isActive: true,
    isFeatured: true,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "mv2",
      productId: "m2",
      sku: "PS-NVY-M",
      size: "M",
      color: "Navy",
      colorHex: "#000080",
      price: 1299,
      compareAtPrice: 2199,
      costPrice: 800,
      stockQuantity: 75,
      isActive: true,
      images: [{
        id: "mi2",
        variantId: "mv2",
        url: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800",
        altText: "Polo Shirt",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 1299,
    maxPrice: 1299,
    avgRating: 4.7,
    reviewCount: 156,
    totalStock: 75
  },
  {
    id: "m3",
    name: "Formal Dress Shirt",
    slug: "formal-white-shirt",
    description: "Professional white dress shirt for office wear",
    categoryId: "2-1-1",
    categoryName: "Formal Shirts",
    tags: ["shirt", "formal", "office wear"],
    isActive: true,
    isFeatured: true,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "mv3",
      productId: "m3",
      sku: "FS-WHT-M",
      size: "M",
      color: "White",
      colorHex: "#FFFFFF",
      price: 1799,
      compareAtPrice: 2999,
      costPrice: 1100,
      stockQuantity: 95,
      isActive: true,
      images: [{
        id: "mi3",
        variantId: "mv3",
        url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800",
        altText: "White Formal Shirt",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 1799,
    maxPrice: 1799,
    avgRating: 4.8,
    reviewCount: 278,
    totalStock: 95
  }
];
var kidsProducts = [
  {
    id: "k1",
    name: "Boys Printed T-Shirt",
    slug: "boys-superhero-tshirt",
    description: "Fun superhero printed t-shirt for boys",
    categoryId: "3-1-2",
    categoryName: "Boys T-Shirts",
    tags: ["kids", "boys", "t-shirt"],
    isActive: true,
    isFeatured: false,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "kv1",
      productId: "k1",
      sku: "BT-BLU-4Y",
      size: "4-5Y",
      color: "Blue",
      colorHex: "#4169E1",
      price: 399,
      compareAtPrice: 699,
      costPrice: 250,
      stockQuantity: 85,
      isActive: true,
      images: [{
        id: "ki1",
        variantId: "kv1",
        url: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800",
        altText: "Boys T-Shirt",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 399,
    maxPrice: 399,
    avgRating: 4.7,
    reviewCount: 145,
    totalStock: 85
  },
  {
    id: "k2",
    name: "Girls Party Frock",
    slug: "girls-floral-frock",
    description: "Beautiful floral frock for special occasions",
    categoryId: "3-2-1",
    categoryName: "Girls Frocks",
    tags: ["kids", "girls", "party wear"],
    isActive: true,
    isFeatured: true,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "kv2",
      productId: "k2",
      sku: "GF-PNK-4Y",
      size: "4-5Y",
      color: "Pink",
      colorHex: "#FF69B4",
      price: 899,
      compareAtPrice: 1499,
      costPrice: 550,
      stockQuantity: 62,
      isActive: true,
      images: [{
        id: "ki2",
        variantId: "kv2",
        url: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800",
        altText: "Girls Frock",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 899,
    maxPrice: 899,
    avgRating: 4.8,
    reviewCount: 198,
    totalStock: 62
  },
  {
    id: "k3",
    name: "Infant Romper Set",
    slug: "baby-cotton-romper",
    description: "Soft cotton romper set for infants",
    categoryId: "3-3",
    categoryName: "Infant Wear",
    tags: ["kids", "infant", "romper"],
    isActive: true,
    isFeatured: true,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "kv3",
      productId: "k3",
      sku: "IR-YEL-3M",
      size: "3-6M",
      color: "Yellow",
      colorHex: "#FFD700",
      price: 599,
      compareAtPrice: 999,
      costPrice: 380,
      stockQuantity: 45,
      isActive: true,
      images: [{
        id: "ki3",
        variantId: "kv3",
        url: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800",
        altText: "Baby Romper",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 599,
    maxPrice: 599,
    avgRating: 4.9,
    reviewCount: 267,
    totalStock: 45
  }
];
var homeTextilesProducts = [
  {
    id: "h1",
    name: "Premium Cotton Bedsheet Set",
    slug: "cotton-bedsheet-king",
    description: "Luxury cotton bedsheet set with pillow covers",
    categoryId: "4-1",
    categoryName: "Bed Sheets",
    tags: ["home", "bedsheet", "cotton"],
    isActive: true,
    isFeatured: true,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "hv1",
      productId: "h1",
      sku: "BS-BLU-K",
      size: "King",
      color: "Blue",
      colorHex: "#4169E1",
      price: 2499,
      compareAtPrice: 3999,
      costPrice: 1600,
      stockQuantity: 38,
      isActive: true,
      images: [{
        id: "hi1",
        variantId: "hv1",
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800",
        altText: "Bedsheet Set",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 2499,
    maxPrice: 2499,
    avgRating: 4.7,
    reviewCount: 234,
    totalStock: 38
  },
  {
    id: "h2",
    name: "Blackout Curtains",
    slug: "blackout-window-curtains",
    description: "Energy saving blackout curtains for bedroom",
    categoryId: "4-3",
    categoryName: "Curtains",
    tags: ["home", "curtains", "blackout"],
    isActive: true,
    isFeatured: true,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "hv2",
      productId: "h2",
      sku: "CU-GRY-7F",
      size: "7ft",
      color: "Grey",
      colorHex: "#808080",
      price: 1899,
      compareAtPrice: 2999,
      costPrice: 1200,
      stockQuantity: 52,
      isActive: true,
      images: [{
        id: "hi2",
        variantId: "hv2",
        url: "https://images.unsplash.com/photo-1616627781431-23c3a9b717be?w=800",
        altText: "Blackout Curtains",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 1899,
    maxPrice: 1899,
    avgRating: 4.8,
    reviewCount: 189,
    totalStock: 52
  },
  {
    id: "h3",
    name: "Decorative Cushion Covers",
    slug: "printed-cushion-covers",
    description: "Set of 5 printed cushion covers",
    categoryId: "4-2",
    categoryName: "Pillow Covers",
    tags: ["home", "cushion", "decorative"],
    isActive: true,
    isFeatured: false,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    variants: [{
      id: "hv3",
      productId: "h3",
      sku: "CC-MLT-16",
      size: "16x16",
      color: "Multi",
      colorHex: "#FF6347",
      price: 799,
      compareAtPrice: 1299,
      costPrice: 500,
      stockQuantity: 95,
      isActive: true,
      images: [{
        id: "hi3",
        variantId: "hv3",
        url: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800",
        altText: "Cushion Covers",
        sortOrder: 1,
        isMain: true
      }]
    }],
    minPrice: 799,
    maxPrice: 799,
    avgRating: 4.5,
    reviewCount: 156,
    totalStock: 95
  }
];
var allProducts = [
  ...womenProducts,
  ...menProducts,
  ...kidsProducts,
  ...homeTextilesProducts
];
var mockCategories = [
  // Women's Section
  {
    id: "1",
    name: "Women",
    slug: "women",
    description: "Elegant collection of women's textiles",
    imageUrl: "/images/categories/women.jpg",
    sortOrder: 1,
    isActive: true,
    productCount: 450,
    children: [
      {
        id: "1-1",
        name: "Sarees",
        slug: "women/sarees",
        description: "Traditional and contemporary sarees",
        imageUrl: "/images/categories/sarees.jpg",
        parentId: "1",
        sortOrder: 1,
        isActive: true,
        productCount: 120,
        children: [
          {
            id: "1-1-1",
            name: "Silk Sarees",
            slug: "women/sarees/silk",
            parentId: "1-1",
            sortOrder: 1,
            isActive: true,
            productCount: 45
          },
          {
            id: "1-1-2",
            name: "Cotton Sarees",
            slug: "women/sarees/cotton",
            parentId: "1-1",
            sortOrder: 2,
            isActive: true,
            productCount: 35
          },
          {
            id: "1-1-3",
            name: "Designer Sarees",
            slug: "women/sarees/designer",
            parentId: "1-1",
            sortOrder: 3,
            isActive: true,
            productCount: 25
          },
          {
            id: "1-1-4",
            name: "Party Wear Sarees",
            slug: "women/sarees/party-wear",
            parentId: "1-1",
            sortOrder: 4,
            isActive: true,
            productCount: 15
          }
        ]
      },
      {
        id: "1-2",
        name: "Chudithars & Salwars",
        slug: "women/chudithars-salwars",
        description: "Comfortable and stylish ethnic wear",
        imageUrl: "/images/categories/chudithars.jpg",
        parentId: "1",
        sortOrder: 2,
        isActive: true,
        productCount: 95,
        children: [
          {
            id: "1-2-1",
            name: "Casual Wear",
            slug: "women/chudithars-salwars/casual",
            parentId: "1-2",
            sortOrder: 1,
            isActive: true,
            productCount: 40
          },
          {
            id: "1-2-2",
            name: "Party Wear",
            slug: "women/chudithars-salwars/party",
            parentId: "1-2",
            sortOrder: 2,
            isActive: true,
            productCount: 30
          },
          {
            id: "1-2-3",
            name: "Office Wear",
            slug: "women/chudithars-salwars/office",
            parentId: "1-2",
            sortOrder: 3,
            isActive: true,
            productCount: 25
          }
        ]
      },
      {
        id: "1-3",
        name: "Kurtis",
        slug: "women/kurtis",
        description: "Modern and traditional kurtis",
        imageUrl: "/images/categories/kurtis.jpg",
        parentId: "1",
        sortOrder: 3,
        isActive: true,
        productCount: 85
      },
      {
        id: "1-4",
        name: "Nightwear",
        slug: "women/nightwear",
        description: "Comfortable nightwear collection",
        imageUrl: "/images/categories/nightwear-women.jpg",
        parentId: "1",
        sortOrder: 4,
        isActive: true,
        productCount: 65
      }
    ]
  },
  // Men's Section
  {
    id: "2",
    name: "Men",
    slug: "men",
    description: "Sophisticated men's textile collection",
    imageUrl: "/images/categories/men.jpg",
    sortOrder: 2,
    isActive: true,
    productCount: 320,
    children: [
      {
        id: "2-1",
        name: "Shirts",
        slug: "men/shirts",
        description: "Formal and casual shirts",
        imageUrl: "/images/categories/shirts.jpg",
        parentId: "2",
        sortOrder: 1,
        isActive: true,
        productCount: 95,
        children: [
          {
            id: "2-1-1",
            name: "Formal Shirts",
            slug: "men/shirts/formal",
            parentId: "2-1",
            sortOrder: 1,
            isActive: true,
            productCount: 40
          },
          {
            id: "2-1-2",
            name: "Casual Shirts",
            slug: "men/shirts/casual",
            parentId: "2-1",
            sortOrder: 2,
            isActive: true,
            productCount: 35
          }
        ]
      },
      {
        id: "2-2",
        name: "T-Shirts",
        slug: "men/t-shirts",
        description: "Comfortable and trendy t-shirts",
        imageUrl: "/images/categories/t-shirts.jpg",
        parentId: "2",
        sortOrder: 2,
        isActive: true,
        productCount: 75,
        children: [
          {
            id: "2-2-1",
            name: "Polo",
            slug: "men/t-shirts/polo",
            parentId: "2-2",
            sortOrder: 1,
            isActive: true,
            productCount: 25
          },
          {
            id: "2-2-2",
            name: "Round Neck",
            slug: "men/t-shirts/round-neck",
            parentId: "2-2",
            sortOrder: 2,
            isActive: true,
            productCount: 30
          }
        ]
      },
      {
        id: "2-3",
        name: "Pants",
        slug: "men/pants",
        description: "Formal and casual pants",
        imageUrl: "/images/categories/pants.jpg",
        parentId: "2",
        sortOrder: 3,
        isActive: true,
        productCount: 65,
        children: [
          {
            id: "2-3-1",
            name: "Formal Pants",
            slug: "men/pants/formal",
            parentId: "2-3",
            sortOrder: 1,
            isActive: true,
            productCount: 25
          },
          {
            id: "2-3-2",
            name: "Jeans",
            slug: "men/pants/jeans",
            parentId: "2-3",
            sortOrder: 2,
            isActive: true,
            productCount: 25
          }
        ]
      }
    ]
  },
  // Kids Section
  {
    id: "3",
    name: "Kids",
    slug: "kids",
    description: "Adorable children's clothing collection",
    imageUrl: "/images/categories/kids.jpg",
    sortOrder: 3,
    isActive: true,
    productCount: 280,
    children: [
      {
        id: "3-1",
        name: "Boys",
        slug: "kids/boys",
        description: "Trendy clothing for boys",
        imageUrl: "/images/categories/boys.jpg",
        parentId: "3",
        sortOrder: 1,
        isActive: true,
        productCount: 125,
        children: [
          {
            id: "3-1-1",
            name: "Shirts",
            slug: "kids/boys/shirts",
            parentId: "3-1",
            sortOrder: 1,
            isActive: true,
            productCount: 35
          },
          {
            id: "3-1-2",
            name: "T-Shirts",
            slug: "kids/boys/t-shirts",
            parentId: "3-1",
            sortOrder: 2,
            isActive: true,
            productCount: 40
          }
        ]
      },
      {
        id: "3-2",
        name: "Girls",
        slug: "kids/girls",
        description: "Beautiful clothing for girls",
        imageUrl: "/images/categories/girls.jpg",
        parentId: "3",
        sortOrder: 2,
        isActive: true,
        productCount: 135,
        children: [
          {
            id: "3-2-1",
            name: "Frocks",
            slug: "kids/girls/frocks",
            parentId: "3-2",
            sortOrder: 1,
            isActive: true,
            productCount: 45
          },
          {
            id: "3-2-2",
            name: "Tops & Bottoms",
            slug: "kids/girls/tops-bottoms",
            parentId: "3-2",
            sortOrder: 2,
            isActive: true,
            productCount: 40
          }
        ]
      },
      {
        id: "3-3",
        name: "Infant Wear (0-2 years)",
        slug: "kids/infant-wear",
        description: "Soft and comfortable baby clothes",
        imageUrl: "/images/categories/infant.jpg",
        parentId: "3",
        sortOrder: 3,
        isActive: true,
        productCount: 20
      }
    ]
  },
  // Home Textiles
  {
    id: "4",
    name: "Home Textiles",
    slug: "home-textiles",
    description: "Premium home textile collection",
    imageUrl: "/images/categories/home-textiles.jpg",
    sortOrder: 4,
    isActive: true,
    productCount: 150,
    children: [
      {
        id: "4-1",
        name: "Bed Sheets",
        slug: "home-textiles/bed-sheets",
        description: "Comfortable and stylish bed sheets",
        imageUrl: "/images/categories/bed-sheets.jpg",
        parentId: "4",
        sortOrder: 1,
        isActive: true,
        productCount: 45
      },
      {
        id: "4-2",
        name: "Pillow Covers",
        slug: "home-textiles/pillow-covers",
        description: "Decorative pillow covers",
        imageUrl: "/images/categories/pillow-covers.jpg",
        parentId: "4",
        sortOrder: 2,
        isActive: true,
        productCount: 35
      },
      {
        id: "4-3",
        name: "Curtains",
        slug: "home-textiles/curtains",
        description: "Beautiful window curtains",
        imageUrl: "/images/categories/curtains.jpg",
        parentId: "4",
        sortOrder: 3,
        isActive: true,
        productCount: 30
      },
      {
        id: "4-4",
        name: "Towels",
        slug: "home-textiles/towels",
        description: "Soft and absorbent towels",
        imageUrl: "/images/categories/towels.jpg",
        parentId: "4",
        sortOrder: 4,
        isActive: true,
        productCount: 40
      }
    ]
  }
];
var mockFeaturedProducts = [
  womenProducts[0],
  // Banarasi Saree
  menProducts[1],
  // Polo Shirt
  kidsProducts[1],
  // Girls Frock
  homeTextilesProducts[0],
  // Bedsheet
  womenProducts[2],
  // Salwar Suit
  menProducts[2]
  // Formal Shirt
];

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the TextTiles public product catalog by keyword. Matches product name, description, category, and tags. Returns id, name, slug, category, price range, rating, and main image.",
  inputSchema: {
    query: z.string().min(1).describe("Keyword to search across the catalog."),
    section: z.enum(["women", "men", "kids", "home"]).optional().describe("Optional section filter."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, section, limit }) => {
    const q = query.toLowerCase();
    const sectionPrefix = { women: "w", men: "m", kids: "k", home: "h" };
    let results = allProducts.filter((p) => {
      const hay = [
        p.name,
        p.description ?? "",
        p.categoryName ?? "",
        (p.tags ?? []).join(" ")
      ].join(" ").toLowerCase();
      if (!hay.includes(q)) return false;
      if (section && !p.id.startsWith(sectionPrefix[section])) return false;
      return true;
    });
    results = results.slice(0, limit ?? 10);
    const shaped = results.map((p) => ({
      id: p.id,
      name: p.name,
      slug: p.slug,
      category: p.categoryName,
      minPrice: p.minPrice,
      maxPrice: p.maxPrice,
      rating: p.avgRating,
      reviewCount: p.reviewCount,
      image: p.variants?.[0]?.images?.[0]?.url
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(shaped, null, 2) }],
      structuredContent: { results: shaped, count: shaped.length }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch full details for a single product from the TextTiles public catalog by slug, including variants, prices, colors, sizes, stock, and images.",
  inputSchema: {
    slug: z2.string().min(1).describe("Product slug (e.g. 'banarasi-silk-saree-red').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const product = allProducts.find((p) => p.slug === slug);
    if (!product) {
      return {
        content: [{ type: "text", text: `No product found with slug "${slug}"` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List TextTiles product categories. Returns top-level sections (Women, Men, Kids, Home Textiles) and their subcategories from the public catalog.",
  inputSchema: {
    parentSlug: z3.string().optional().describe("If provided, return subcategories under this parent slug instead of the top level.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ parentSlug }) => {
    const shape = (c) => ({
      id: c.id,
      name: c.name,
      slug: c.slug,
      childCount: Array.isArray(c.children) ? c.children.length : 0
    });
    let items;
    if (!parentSlug) {
      items = mockCategories.map(shape);
    } else {
      const parent = findBySlug(mockCategories, parentSlug);
      items = (parent?.children ?? []).map(shape);
    }
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { categories: items }
    };
  }
});
function findBySlug(list, slug) {
  for (const c of list) {
    if (c.slug === slug) return c;
    if (c.children) {
      const hit = findBySlug(c.children, slug);
      if (hit) return hit;
    }
  }
  return null;
}

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "texttiles-mcp",
  title: "TextTiles MCP",
  version: "0.1.0",
  instructions: "Public tools for the TextTiles digital textile showroom. Use `list_categories` to explore Women/Men/Kids/Home Textiles sections, `search_products` to find items by keyword, and `get_product` to fetch full details by slug. All data is from the public product catalog \u2014 no authentication required.",
  tools: [search_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
